### ISSUE TITLE
DatePicker bug. A client can pick 00:00 appointment in unavailable day. 

### ISSUE THREAD

**Issue by KornelijusGlinskas** [nfqakademija/nnizer#30]
It needs to be fixed before the contractor page finish.

**Comment by dominykasmurauskas** [comment]
https://github.com/nfqakademija/nnizer/pull/32
@KornelijusGlinskas minor fixes should be made in the front-end, endpoint now returns null:
![image](https://user-images.githubusercontent.com/50072263/70142679-77e17a00-16a2-11ea-8897-097e73e41ebb.png)

**Comment by dominykasmurauskas** [comment]
Resolved
