### ISSUE TITLE
Missing translation. Need to be added.

### ISSUE THREAD

**Issue by KornelijusGlinskas** [nfqakademija/nnizer#48]
<img width="1279" alt="Screenshot 2019-12-13 at 11 55 27" src="https://user-images.githubusercontent.com/36265050/70791390-b44a5f80-1d9f-11ea-9a38-efd2e9dbd086.png">

**Comment by dominykasmurauskas** [comment]
Resolved in https://github.com/nfqakademija/nnizer/commit/7129038e07163268fb82e3418e6db62a2b51ea48
