### ISSUE TITLE
Star filters on mobile view are separated in two lines. Not priority issue

### ISSUE THREAD

**Issue by tadas-nfq** [nfqakademija/nnizer#68]
![Screenshot from 2019-12-16 22-28-47](https://user-images.githubusercontent.com/57136491/70940961-1b903a00-2054-11ea-952c-849787317809.png)

![Screenshot from 2019-12-16 22-34-09](https://user-images.githubusercontent.com/57136491/70941008-3498eb00-2054-11ea-8d33-5a30bcd020d7.png)

**Comment by KornelijusGlinskas** [comment]
I didn't know how to handle it at that moment. Putting all-star filters in one line seemed to be a bit too busy, so I've left like this. Any suggestion of how it should be handled though?

**Comment by tadas-nfq** [comment]
On smaller phones 5 buttons in one row would be too much. So maybe leave it like it is.
But maybe in larger phones like in the bottom picture it could be in one row, just a little bit smaller?
Also it would be nice to align second line buttons to the first row. Because now second button looks different :)

**Comment by KornelijusGlinskas** [comment]
Oh yeah, indeed it is! Nice catch, Tadas. I'll give a look if I'll finish other important things till 22pm :)

**Comment by KornelijusGlinskas** [comment]
made all stars filters in one line no matter what device viewport. #97
