### ISSUE TITLE
413 error is not handled.

### ISSUE THREAD

**Issue by KornelijusGlinskas** [nfqakademija/nnizer#73]
It happens when I try to upload bigger file than 2mb. Can we handle it somehow? Just like 404 and 500. 
<img width="1393" alt="Screenshot 2019-12-17 at 13 59 50" src="https://user-images.githubusercontent.com/36265050/70993866-9b121d80-20d5-11ea-9133-6e94daaf6ee9.png">

**Comment by dominykasmurauskas** [comment]
Resolved in https://github.com/nfqakademija/nnizer/commit/f7e44737a7e22fb2cd7924de4efcb35a1570aa5a

**Comment by KornelijusGlinskas** [comment]
@dominykasmurauskas  is it possible to add an image in that landing page and style a bit?

**Comment by KornelijusGlinskas** [comment]
@dominykasmurauskas explained that there won't be any error because validation now is done. My bad.
