### ISSUE TITLE
Reviews email template stars styling

### ISSUE THREAD

**Issue by dominykasmurauskas** [nfqakademija/nnizer#80]
Please add star icons on review email. This should not be like that:
![image](https://user-images.githubusercontent.com/50072263/71029266-b9007200-2117-11ea-94f7-3b26aed80320.png)

Also, it would be best if you could remove these in this email:
![image](https://user-images.githubusercontent.com/50072263/71029423-02e95800-2118-11ea-8a2a-d1c310957ed1.png)

To test it on your end, add a reservation, set is as verified, change the visitDate to a past time and launch bin/console app:send-review-links
It will deliver a review email for you. Don't forget links in review email use the real host, not localhost, so you may have to change it manually.

**Comment by KornelijusGlinskas** [comment]
#71 fixed :)
